/**
 * Compile-time configuration overrides for dav1d AV1 decoder WASM build.
 *
 * This file is used as config.h (via -include) to replace the meson-generated
 * config.h that dav1d normally expects. It disables ASM, threading, and
 * features that require platform-specific support.
 *
 * Included via `emcc -include dav1d_overrides.h` so that `#include "config.h"`
 * in every dav1d source file picks up these definitions.
 */

#ifndef DAV1D_OVERRIDES_H
#define DAV1D_OVERRIDES_H

/* Version info (normally generated by meson) */
#define DAV1D_VERSION "1.5.1"

/* Disable all architecture-specific ASM */
/* (no ARCH_X86, ARCH_AARCH64, etc. defined = pure C fallback) */

/* Disable threading — single-threaded WASM build */
/* #undef HAVE_PTHREAD_H */
/* #undef HAVE_PTHREAD_NP_H */

/* Standard C features available in Emscripten */
#define HAVE_STDATOMIC_H 1
#define HAVE_DLSYM 0

/* Required: tell dav1d we have unistd.h (Emscripten provides it) */
#define HAVE_UNISTD_H 1

/* Required: I/O functions — not used but referenced */
#define HAVE_IO_H 0

/* Memory alignment — Emscripten provides posix_memalign */
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_MEMALIGN 0
#define HAVE_ALIGNED_ALLOC 0

/* Logging to stderr — safe in WASM (goes to fd_write stub) */
#define CONFIG_LOG 1

/* Stack alignment — not relevant for WASM */
#define STACK_ALIGNMENT 16

/* Bit depths to support */
#define CONFIG_8BPC 1
#define CONFIG_16BPC 1

/* Trim size: disable film grain application at the template level
 * (we only need QP values, not pixel output quality) */
/* Actually keep it — dav1d's internal decode path expects it */

#endif /* DAV1D_OVERRIDES_H */
